name: test

on:
  push:
    branches: [master]
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm i --prefer-offline
      - run: pnpm test
      - run: pnpm run lint
      - run: pnpm run lint:ci
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint.sarif
